### ISSUE TITLE
Speed up runPostCrab.py

### ISSUE THREAD

**Issue by OlivierBondu** [cp3-llbb/GridIn#12]
It is awfully too slow for big samples (e.g., TTbar)

**Comment by OlivierBondu** [comment]
I suspect this was due to the size of the outlog... in case of TTbar there was a lot of 'cannot find signal MC truth' kind of output for every single event in the analyzer I was running

if no one else can confirm, this may be closed ?

**Comment by blinkseb** [comment]
I found some times to investigate this, since it's still relevant. The culprit is `crab report`, which takes ages to do it's job. I found the reason, and opened a PR in crab3 repo:

https://github.com/dmwm/CRABClient/pull/4579

Hopefully it'll be accepted and merged quickly. Otherwise it should be possible to setup our own private crab release and apply the patch on top of it.

**Comment by OlivierBondu** [comment]
great, thanks !

**Comment by AlexandreMertens** [comment]
Hello,

How are you doing this task now that crab3 is not yet updated?
It is really annoying to wait more than 20 minutes and then have the following message because you don't answer fast enough...

```
##### Figure out the code(s) version
Enter passphrase for key '/home/fynu/amertens/.ssh/id_rsa': 
Received disconnect from 192.30.252.131: 11: Bye Bye
fatal: Could not read from remote repository.
```

**Comment by blinkseb** [comment]
I'm not sure if this is what you mean, but the fix is already included in runPostCrab, see https://github.com/cp3-llbb/GridIn/commit/5a8ba92c151e7c387f0c4ef5abc9d9488a3c5701 ; Maybe you just need to pull?

For the second issue, I suggest you to use an ssh-agent on your computer and forward it when connecting to ingrid (see https://developer.github.com/guides/using-ssh-agent-forwarding/ for some documentation).

**Comment by OlivierBondu** [comment]
there is also https://cp3.irmp.ucl.ac.be/projects/cp3admin/wiki/UsersPage/Support/CP3/IT/SshKeys that can help :)
