### ISSUE TITLE
Update datasets to MiniAOD v2

### ISSUE THREAD

**Issue by OlivierBondu** [cp3-llbb/GridIn#40]
- [x] data
- [x] DY
- [x] QCD
- [x] SM Higgs
- [x] Single top
- [x] TTbar
- [x] TTV 
- [x] VV
- [x] WJets
- [x] ggX0HH
- [x] ggX2HH

(I am currently working on a first round, but not everything is here yet, should be coming this week at this pace, see [these slides](https://indico.cern.ch/event/452903/session/0/contribution/67/attachments/1173019/1694372/15-10-19_CMSweek_PPD.pdf#page=13))

**Comment by swertz** [comment]
Thanks! :+1: 

For data, do we drop completely runB? runC will also take some time before it's ready... And runD has to be split in two since part of it has PromptReco with already miniAODv2. 
Btw, I think we can also drop SingleLepton datasets for now? They're not going to be used in the near future anyway (until we figure an easy way to avoid double couting between datasets)...

**Comment by OlivierBondu** [comment]
fine with me, I was looking at MC first (the part I know best ;) ), do you wish to do data ? (including removing the deprecated files as you suggest)

**Comment by swertz** [comment]
Sure, I can have a look tomorrow! So unless someone complains I'll remove runB and SingleLepton datesets...

**Comment by OlivierBondu** [comment]
data addressed in #42
